version: "3.8"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    container_name: kgp_sales-postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kgp_sales
    ports:
      - 5442:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "kgp_sales", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  keycloak: