version: "3.8"

services:
  mysql:
    container_name: ksm-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=kgp_sales
    security_opt:
      - seccomp:unconfined
    ports:
      - "3336:3306"