version: "3.8"

services:
  mocker:
    image: node:18
    container_name: ksm-mocker
    command: sh .docker/entrypoint.dev.sh
    env_file:
      - .env.example
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
